### ISSUE TITLE
Consent is given by DataSubject, not to Datasubject

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-consent#11]
**Description**
In the current version of the model there is a relation Consent.isProvidedToAgent. As an Agent can be not only a DataController (and also a DataRequester but in issue #9 we argue that this class is unnecessary) but also a DataSubject, it is now possible for a DataSubject to ask Consent for the Processing of PersonalData (of a DataSubject). Altough it is possible of course that someone that has been the DataSubject in a previous request for Consent, the moment an Agent asks himself for Consent he becomes a DataController and is no longer the DataSubject. (One cannot be DataSubject and DataController for the same Consent.)

**Solution**
Remove the association Consent->Agent.

**Comment by michaelgeamanu** [comment]
The association has been deleted and the class Agent is shown differently in the model to improve the clarity of the model.
