### ISSUE TITLE
DataSubject should be subclass of Person 

### ISSUE THREAD

**Issue by GeertThijs** [Informatievlaanderen/OSLOthema-consent#12]
**Description**
MinorDataSubject, while also being a subclass of Datasubject, is now defined as a subclass of Person. It should be Datasubject that is defined as a subclass of Person. Which infers that also a MinorDataSubject is a Person.

**Solution**
Make DataSubject a subclass of Person in stead of MinorDataSubject.

**Comment by GeertThijs** [comment]
Simplified class diagram to illustrate the proposed solution:
![Illustration03](https://user-images.githubusercontent.com/22620291/144930474-0b93ad82-e1b8-417c-a179-2edef2558224.jpg)

**Comment by michaelgeamanu** [comment]
This was done accordingly.
