### ISSUE TITLE
Periode bepalen voor de (personal)data 

### ISSUE THREAD

**Issue by FilipBorl** [Informatievlaanderen/OSLOthema-consent#18]
In het huidige model is het mogelijk om meerdere datasets te koppelen aan één instemming maar het is niet mogelijk deze te bepalen met voorwaarden zoals de periode. Dit is essentiele functionaliteit voor verschillende van onze use cases. 
vb: Ik heb de laatste drie loonbrieven nodig of de loonbrieven van de laatste drie maanden of loonbrieven van minsten drie maanden niet ouder dan ... 

Een mogelijke oplossing zou kunnen zijn de periode toe te voegen als een attribuut aan de klasse personal data zoals besproken tijdens onze call van 7/1/22.

**Comment by michaelgeamanu** [comment]
Om dit aan te pakken werd de klasse "Filter" toegevoegd aan het model. Deze klasse maakt het mogelijk om persoonlijke data verder te filteren op basis van verschillende gegevens zoals een periode. Op deze manier kan de persoonlijke data die in scope ligt van de consent verder verfijnd.
