### ISSUE TITLE
Filter > period of time

### ISSUE THREAD

**Issue by bertvannuffelen** [Informatievlaanderen/OSLOthema-consent#28]
Hi

What is the semantics for https://purl.eu/doc/applicationprofile/consent/#Filter property period of time?
The definition is just the label.

That is not a definition. 
Is it the validity period of the filter?
Is it the period of creation of the filter?

**Comment by michaelgeamanu** [comment]
The definition is changed to: "A period of time defining the time interval the personal data should originate from."
