### ISSUE TITLE
Contextual requirements for the Consent to be valid

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLOthema-consent#4]
How do we model contextual requirements that need to be satisfied for the Consent to be valid, e.g. medical staff are only allowed to access my medical records in case of a medical emergency when I’m not able to give explicit consent myself.

Inspiration can be drawn from example 3 in [GConsent](https://openscience.adaptcentre.ie/ontologies/GConsent/docs/ontology#usage-adoption), where this is considered to be an implicit consent through delegation.

**Comment by michaelgeamanu** [comment]
Just like the credential based consent (issue nr. 3), the contextual requirements will be covered by the CCCEV datamodel.
