### ISSUE TITLE
Relationship between data subject and data consumer versus purpose

### ISSUE THREAD

**Issue by dimi-schepers** [Informatievlaanderen/OSLOthema-consent#5]
During the workshop dd. 2021-09-23, the importance of the nature of the relationship between the data subject and the data consumer was mentioned. The willingness to give consent or not can depend on it. To be able to better understand where and how relationships fit into the story, we would like to get some more use cases that highlight and clarify the difference between the relationship and the purpose.

This example was given in the workshop: _I want to share my wage with a certain bank because I want a loan, not because I also already have a bank account there. So, it is important that they have access because I want a loan, not because I have a bank account. Note that this also implies that someone can have several relationships with the same organisation._

It was also mentioned that purpose and/or relationship should be very specific. ‘Getting a loan’ is not the same as ‘getting a mortgage loan for my first house’. We need a very clear and unambiguous way to explain the context in which we can use the data subject’s data.

We invite the community to provide additional cases and examples to clarify the importance of specifying the relationship between the data subject and data consumer, in addition to specifying the purpose of the consent.

**Comment by michaelgeamanu** [comment]
The purpose is the actual service you want to get. A relationship could be broader than a purpose and help to fulfil a specific transaction. There are 2 objectives linked to the purpose:
1. define which information the requester needs; and
2. define what can be done with the information that is shared.

The purpose is therefore added as an attribute of the class PersonalDataHandling and is left open to fill in as detailed as necessary. While the relationship between the DataSubject and DataRequester is indicated in a more general way.
